### ISSUE TITLE
Use this package in Deno?

### ISSUE THREAD

**Issue by shah** [mfbx9da4/deep-email-validator#10]
@mfbx9da4 great library! Do you have any plans to get it to work in Deno, we've love to use it there and directly from the browser instead of just server side NodeJS.

Please note that if you make some minor adjustments it could work in the browser as well as Deno:

https://www.skypack.dev/view/deep-email-validator

![image](https://user-images.githubusercontent.com/47497/102364702-bfbd0180-3f84-11eb-8bf8-2451a68d9977.png)

**Comment by mfbx9da4** [comment]
Hey thanks @shah - they would be great features. In the short term I have no intention of building them but PRs are very welcome!
