### ISSUE TITLE
Module not found: DNS

### ISSUE THREAD

**Issue by thanhtran0302** [mfbx9da4/deep-email-validator#12]
I had this message when using the library

![image](https://user-images.githubusercontent.com/4073197/102373202-3cb99c80-3fc0-11eb-824d-a00cd36d04ef.png)

My code:
```javascript
import validate from 'deep-email-validator';

  const onSubmit = async (event: FormEvent<Element>) => {
    event.preventDefault();

    const res = await validate(email);
    console.log({ res });
  };
```

**Comment by mfbx9da4** [comment]
this is only to be sued in nodejs environment not in the browser
