### ISSUE TITLE
SMTP Timeout for valid SMTP servers like Gmail.com, etc

### ISSUE THREAD

**Issue by shaikh-shahid** [mfbx9da4/deep-email-validator#16]
Hi,

For every email even with valid SMTP server, its giving timeout error and returning valid:false for SMTP. 

I tested with this personal email of mine rwtc66@gmail.com

and output is

```
{
  valid: false,
  validators: {
    regex: { valid: true },
    typo: { valid: true },
    disposable: { valid: true },
    mx: { valid: true },
    smtp: { valid: false, reason: 'Timeout' }
  },
  reason: 'smtp'
}
```

**Comment by mfbx9da4** [comment]
Probably this is an issue with your firewall or server config. Check locally or no a different network
