### ISSUE TITLE
SMTP always returns with a Timeout error

### ISSUE THREAD

**Issue by rahulshial** [mfbx9da4/deep-email-validator#18]
Hi,
The email validation always returns with a 'Timeout' reason, which turns the valid flag to false. I am running a MySql DB with a React frontend on Ubuntu 20.04 on NodeJs.

If SMTP is defaulted to False, then all email addresses though invalid are taken as valid.

Please advise.

**Comment by mfbx9da4** [comment]
Likely the host machine's port is not open to connect to an smtp server
