### ISSUE TITLE
Do not support some domains, like .cn, .lv, .shop

### ISSUE THREAD

**Issue by bulog** [mfbx9da4/deep-email-validator#29]
Hi, I just checked some TLD, such like .cn, .site, .lv, .inc, .ltd, .shop. all these failed for the reason "typo"

``` javascript
const { validate } = require('deep-email-validator');

async function Validate(email) {
    const res = await validate({
        email: email,
        sender: 'test@hotmail.com',
        validateRegex: true,
        validateMx: false,
        validateTypo: true,
        validateDisposable: true,
        validateSMTP: false,
    });
    console.log(email, res.valid, res.valid ? '': res.reason);
}

const emails = [
    'test@domain.cn', 
    'test@domain.de', 
    'test@domain.com', 
    'test@domain.site',
    'test@domain.lv',
    'test@domain.inc',
    'test@domain.ltd',
    'test@domain.store',
    'test@domain.shop'
];
emails.forEach(x => {
    Validate(x);
});
```

## result as
```
test@domain.cn false typo
test@domain.site false typo
test@domain.lv false typo
test@domain.inc false typo
test@domain.ltd false typo
test@domain.shop false typo
test@domain.de true
test@domain.com true
test@domain.store true
```

**Comment by bulog** [comment]
the module `mailcheck`, by default only support these TLDs
`defaultTopLevelDomains: ["com", "com.au", "com.tw", "ca", "co.nz", "co.uk", "de",
    "fr", "it", "ru", "net", "org", "edu", "gov", "jp", "nl", "kr", "se", "eu",
    "ie", "co.il", "us", "at", "be", "dk", "hk", "es", "gr", "ch", "no", "cz",
    "in", "net", "net.au", "info", "biz", "mil", "co.jp", "sg", "hu", "uk"],
`

**Comment by utob-ir** [comment]
@mfbx9da4 Would you mind updating the library on npm? We are using this package in production and it needs extra effort to use latest updates though.
