### ISSUE TITLE
Axios 0.19.2 still being used on NPM

### ISSUE THREAD

**Issue by r9119** [mfbx9da4/deep-email-validator#34]
On the NPM package it still relies on axios  0.19.2.

![image](https://user-images.githubusercontent.com/59576343/129526551-544d58d2-e89d-47ce-8a47-1286e536f92c.png)

![image](https://user-images.githubusercontent.com/59576343/129526810-75261659-2957-49ec-bef3-267bb9831201.png)

**Comment by mfbx9da4** [comment]
fixed
