### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by samit59** [mfbx9da4/deep-email-validator#35]
0|server   | function promiseRejectHandler(type, promise, reason) {
0|server   |                              ^
0|server   |
0|server   | RangeError: Maximum call stack size exceeded
0|server   | RangeError: Maximum call stack size exceeded
0|server   |     at formatWithOptions (internal/util/inspect.js:1876:27)
0|server   |     at format (internal/util/inspect.js:1819:10)
0|server   |     at getMessage (internal/errors.js:367:43)
0|server   |     at new NodeError (internal/errors.js:263:23)
0|server   |     at doWrite (_stream_writable.js:399:19)
0|server   |     at writeOrBuffer (_stream_writable.js:387:5)
0|server   |     at Socket.Writable.write (_stream_writable.js:318:11)

**Comment by micalevisk** [comment]
could you please try changing

https://github.com/mfbx9da4/deep-email-validator/blob/0ad7a5010b5859e469223099960a8aff0d1f25c6/src/smtp/smtp.ts#L31

by

```ts
socket.once('fail', msg => { 
```

**Comment by mfbx9da4** [comment]
great catch should definitely should do this! Any chance you could make a PR?
