### ISSUE TITLE
It doesn't work on live server. 

### ISSUE THREAD

**Issue by developersaif** [mfbx9da4/deep-email-validator#37]
When I validate it works on the local server but it doesn't work on the live server.

**Comment by mfbx9da4** [comment]
probably you haven't opened the correct ports

**Comment by developersaif** [comment]
> probably you haven't opened the correct ports

I don't think there is a need port because it just validates the email if I put email. But the port is 25  on the live server. 
Thanks.

**Comment by puremana** [comment]
I'm also having this issue on my live server (AWS ubuntu 20.04 ec2 instance). What ports specifically should I have open? Do I need 25 or 587?

Edit: I have just read that Google has blocked the IP range of EC2's as there is a history of spam abuse from EC2 instances. Is this the case then?

**Comment by kumarajay0412** [comment]
were you able to resolve this ?
