### ISSUE TITLE
No handling for close event in smtp validation

### ISSUE THREAD

**Issue by StructByLightning** [mfbx9da4/deep-email-validator#39]
There's no event handler for the close event in the smtp validator. If you give it the email steven.zajack@chase.com it'll never resolve its promise and your script will exit without an error.

There should be a block like this:
```
    socket.on("close", (err)=>{
      //resolve the promise with something
    })
```
in src/smtp/smtp.ts

**Comment by gagan-bansal** [comment]
For quick fix I added in `node_modules/deep-email-validator/dist/smtp/smtp.js`

```javascript
socket.on('close', () => {                                     
   r(output_1.createOutput('smtp', 'Socket closed'));           
})
```

Thank you @StructByLightning  for pointing out.

I am not familiar to TS, so someone has to make pull request with test case.

**Comment by meabed** [comment]
I have re-wrote this in typescript with wider enhancements to the features as I am using it.
Feel free to use it here => https://github.com/devmehq/email-validator-js
