### ISSUE TITLE
what are the maximum requests per month?

### ISSUE THREAD

**Issue by rohan2734** [mfbx9da4/deep-email-validator#50]
what are the maximum requests per month?

**Comment by mfbx9da4** [comment]
There are none, this is just a javascript library. You import it and use it on your servers

**Comment by rohan2734** [comment]
ok , it is not working on nodejs, you closed the issue , why?

**Comment by mfbx9da4** [comment]
It should work on nodejs, send me a minimal failing github repo and I can take a look. Doubt this is an issue with the library which is why I closed
