### ISSUE TITLE
what is this sender option?

### ISSUE THREAD

**Issue by devSajan** [mfbx9da4/deep-email-validator#52]
here we have email and sender in options,
email: 'name@example.org',
sender: 'name@example.org'

if we are aws ses so do we need to add aws mail in the sender option or it will be the same as email like shown in the doc example?

**Comment by mfbx9da4** [comment]
Sender is for when you are contacting the mailbox of the recipient you need to provide a sender address when doing that in compliance with the SMTP protocol

https://github.com/mfbx9da4/deep-email-validator/blob/master/src/smtp/smtp.ts#L45

The default is simply `name@example.org`

https://github.com/mfbx9da4/deep-email-validator/blob/cefb37abc6e42d3a1551d38f9706d4ff538226e5/src/options/options.ts#L3

Probably you don't care about the sender option and it should work just fine.
