### ISSUE TITLE
Production Server is not able to find api/emailVerifier

### ISSUE THREAD

**Issue by swatisrivs** [mfbx9da4/deep-email-validator#8]
Hi ,
I have deployed my app (that is simple form to verify email in react) on  digital ocean.
I am using nginx. iI have installed ur module on my server also.

My verifier works perfect on localhost.

My problem is when i enter email address and enter submit, i get 404 ERROR.

When i go to https://www.mydomain/api/emailVerifier. i get 404 not found,

this is code from my app.js

handleSubmit = async e => {
    e.preventDefault();
    const response = await fetch('/api/emailVerifier', {
      method: 'POST',
     // body: this.state,
      headers: {
        'Content-Type': 'application/json',
      },

      body: JSON.stringify({ post: this.state.post }),

    });
    const body = await response.text();
    
    this.setState({ responseToPost: body });
  };

Thanks

**Comment by mfbx9da4** [comment]
Most likely nothing to do with this library. Probably your backend is not deployed correctly or you are trying to access it with the wrong URL

**Comment by swatisrivs** [comment]
thanks, can u guide that for production it should be like this

andleSubmit = async e => {
e.preventDefault();
const response = await fetch('https:www.example.com/api/emailVerifier', {

....}

as tested with sample node file..my production serevr works perfect...I know its nt library issue. I am new to web development..Can u guide me more on this

**Comment by mfbx9da4** [comment]
First create another route which you know works and returns "hi". After that you can look into routing and verifying this other verification route
